// Чтобы добавить ролик к карточке, укажите в нужной записи video:
// 'https://kinescope.io/…' или 'https://vk.com/video…'. Плеер появится на странице туториала.
const tutorials = [
  {id:'bracelet',title:'Бархатный браслет с царской вышивкой',video: 'https://vkvideo.ru/video-232284923_456239255', image:'assets/bracelet_tut.png',minutes:300,time:'4–6 часов',level:'Средняя сложность',budget:'600–1 200 ₽',category:'Аксессуары',tags:['Вышивки','Украшения'],description:'Пыльно-розовый бархатный браслет с вытянутым растительным орнаментом, золотистой вышивкой и цветными акцентами. Подходит также как брелок или подвеска для сумки.',materials:'Бархатная лента, мулине или шелковые нити, золотистый бисер, карабин и кольца, игла, булавки, ножницы, флизелин и швейная машина.',history:'',steps:['Выкроить бархатную полоску нужной длины.','Закрепить водорастворимый флизелин и перенести симметричный растительный узор.','Вышить центральный стебель и листья золотыми нитями.','Добавить бордовые и синие бутоны, при желании — бисер.','Растворить флизелин, обработать края и установить кольца с карабином.']},
  {id:'foot',title:'Стальной анклет по марийским мотивам',image:'assets/foot_tut.png',minutes:90,time:'1–2 часа',level:'Низкая сложность',budget:'350–800 ₽',category:'Аксессуары',tags:['Украшения','Подарки'],description:'Лёгкий многослойный анклет с металлическими подвесками и жемчужными акцентами, адаптирующий этнические мотивы под современное украшение.',materials:'Тонкая металлическая цепочка, бусины под жемчуг, круглые подвески, соединительные кольца, карабин, удлинительная цепочка, плоскогубцы и круглогубцы.',history:'Марийские мотивы.',steps:['Измерить обхват щиколотки и отрезать цепочку с запасом.','Разложить подвески и бусины в желаемом ритме.','Закрепить элементы соединительными кольцами.','Добавить второй свободный ряд цепочки.','Установить карабин и проверить посадку.']},
  {id:'jacket',title:'Вышивка крестом на жакете по мотивам Калужского вышивания',image:'assets/jacket_tut.png',minutes:240,time:'3–5 часов',level:'Средняя сложность',budget:'400–900 ₽ без учёта жакета',category:'Одежда',tags:['Вышивки','Кастомизация'],description:'Современный жакет с небольшим традиционным вышитым мотивом — неброский способ интегрировать народное декоративное искусство в повседневный образ.',materials:'Готовый жакет, мулине, водорастворимая или накладная канва, игла, пяльцы, стабилизатор, ножницы, мел и булавки.',history:'По мотивам Калужского вышивания.',steps:['Выбрать орнамент для груди или кармана.','Закрепить водорастворимую канву и перенести схему.','Последовательно вышить мотив крестом.','Закрепить нити с изнанки и удалить канву.','Аккуратно отпарить участок с изнаночной стороны.']},
  {id:'jeans',title:'Оформление пояса джинсов в технике Торжокского золотого шитья',image:'assets/jeans_tut.png',minutes:480,time:'6–10 часов',level:'Высокая сложность',budget:'600–1 300 ₽ без учёта джинсов',category:'Одежда',tags:['Вышивки','Кастомизация'],description:'Тёмные джинсы с рельефным золотым растительным орнаментом на поясе — современная интерпретация торжокского золотного шитья.',materials:'Джинсы, золотная или металлизированная нить, шёлковая нить, шнур для настила, воск, иглы, пяльцы, калька и портновский мел.',history:'Торжокские узоры — сложные растительные орнаменты со стилизованными цветами, листьями, бутонами, бордюрами и завитками.',steps:['Перенести растительный мотив на пояс джинсов.','Натянуть участок ткани в пяльцах.','Создать объёмный настил по форме листьев и бутонов.','Уложить золотную нить и закреплять её в технике в прикреп.','Закрепить концы с изнанки и отпарить ткань.']},
  {id:'notecase',title:'Сумка-чехол для ноутбука или планшета из гобелена с национальным орнаментом',image:'assets/notecase_tut.png',minutes:300,time:'4–6 часов',level:'Средняя сложность',budget:'800–1 500 ₽',category:'Аксессуары',tags:['Шитьё','Для дома'],description:'Мягкий защитный чехол для ноутбука или планшета из плотного гобелена с цветочным орнаментом и текстильной завязкой.',materials:'Гобелен, хлопковая подкладка, термостёжка или синтепон, киперная лента, булавки, игла, швейная машина и портновские ножницы.',history:'',steps:['Постирать и прогладить ткань.','Снять размеры устройства и построить выкройку.','Вырезать детали из гобелена, подкладки и утеплителя.','Простегать заготовку и стачать боковые стороны.','Обработать края и пришить текстильные завязки.']},
  {id:'pin',title:'Брошь, вдохновлённая чукотским национальным костюмом',image:'assets/pin_tut.png',minutes:240,time:'3–5 часов',level:'Средняя сложность',budget:'500–1 000 ₽',category:'Аксессуары',tags:['Украшения','Бисероплетение'],description:'Круглая сине-белая брошь с кабошоном, концентрическими рядами бисера, текстильными лучами и длинной кистью.',materials:'Кабошон, плотный фетр, бисер, мулине, крючок, экокожа или замша, основа для броши, игла, ножницы и клей.',history:'Мотивы народов Севера отличаются круглыми формами-солнцами, лучевой бахромой и центральными камнями-кабошонами.',steps:['Приклеить кабошон на фетровую основу.','Обшить его бисером концентрическими рядами.','Сформировать лучевую бахрому из мулине.','Укрепить изнанку и сделать длинную кисть.','Закрепить застёжку и закрыть изнанку кожей.']},
  {id:'pin2',title:'Брошь, вдохновлённая элементами калмыцкого национального костюма',image:'assets/pin2_tut.png',minutes:330,time:'4–7 часов',level:'Высокая сложность',budget:'600–1 200 ₽',category:'Аксессуары',tags:['Украшения','Вышивки'],description:'Компактная брошь на чёрном бархате с объёмным золотым цветком, бисером и декоративным золотым контуром.',materials:'Чёрный бархат, фетр, картонная основа, золотые нити, бисер, канитель, основа для броши, кожа, иглы, ножницы и клей.',history:'Элементы калмыцкого национального костюма.',steps:['Перенести растительный эскиз на чёрный бархат.','Вышить лепестки и листья золотой гладью.','Выполнить стебли и завитки золотым шнуром.','Добавить бисер, укрепить основу и установить застёжку.','Закрыть изнанку и обшить край канителью.']},
  {id:'teapot',title:'Роспись заварочного чайника в технике витраж',image:'assets/teapot_tut.png',minutes:210,time:'3–4 часа активной работы + сушка',level:'Средняя сложность',budget:'700–1 500 ₽ без учёта чайника',category:'Для дома',tags:['Роспись','Декор'],description:'Прозрачный стеклянный чайник с яркой витражной росписью из цветов, листьев и симметричных декоративных завитков.',materials:'Стеклянный чайник, витражные краски, контур по стеклу, спирт, ватные палочки, тонкие кисти, малярный скотч и салфетки.',history:'Традиционные орнаменты, яркие цвета и сказочные мотивы со стилизованными бутонами, завитками и листьями.',steps:['Вымыть и обезжирить стекло.','Нанести контур симметричного орнамента.','Заполнить элементы витражной краской.','Повторить мотив на крышке и исправить неровности.','Высушить работу и при необходимости выполнить термозакрепление.']},
  {id:'top',title:'Приталенный топ с татарским/казахским мотивом в технике объёмной вышивки',image:'assets/top_tut.png',minutes:600,time:'8–12 часов',level:'Высокая сложность',budget:'800–1 800 ₽ без учёта топа',category:'Одежда',tags:['Вышивки','Кастомизация'],description:'Светлый приталенный топ с выразительной цветной растительной вышивкой, проходящей асимметрично вдоль передней части изделия.',materials:'Однотонный топ, мулине и шёлковые нити, золотая канитель, бисер, фетр, стабилизатор, иглы, пяльцы, ножницы и маркер.',history:'Татарский/казахский мотив.',steps:['Подготовить крупный вертикальный растительный мотив.','Перенести рисунок на стабилизатор и закрепить его на топе.','Создать настил под крупными элементами.','Вышить стебли, контуры, листья и цветы.','Добавить канитель или бисер и удалить стабилизатор.']},
  {id:'top2',title:'Приталенный топ с вышивкой татарского мотива в технике гладь',image:'assets/top_tut2.png',minutes:390,time:'5–8 часов',level:'Средняя сложность',budget:'400–900 ₽ без учёта топа',category:'Одежда',tags:['Вышивки','Кастомизация'],description:'Молочный приталенный топ с деликатной однотонной растительной вышивкой, создающей фактуру без яркого цветового контраста.',materials:'Однотонный светлый топ, мулине или шёлковые нити, флизелин, игла, пяльцы, ножницы, маркер и стабилизатор.',history:'Татарский мотив.',steps:['Выбрать мотив и определить его расположение на топе.','Перенести рисунок на водорастворимый флизелин.','Выполнить контуры стебельчатым швом.','Заполнить листья и лепестки гладью.','Удалить стабилизатор и отпарить вышивку с изнанки.']},
  {id:'wool',title:'Набор ватных украшений в русской стилистике',image:'assets/wool_tut.png',minutes:240,time:'3–5 часов активной работы + сушка',level:'Средняя сложность',budget:'400–900 ₽ за набор',category:'Подарки',tags:['Декор','Новый год'],description:'Набор миниатюрных ватных украшений в русской стилистике: матрёшки, самовар, домик и традиционная выпечка, расписанные вручную.',materials:'Медицинская вата, ПВА или клейстер, фольга, проволока, кисти, ножницы, акриловые краски, лак, джут и атласные ленты.',history:'Ватные игрушки — классика новогоднего оформления с тёплой энергетикой ретро-стиля.',steps:['Сформировать основу игрушек из фольги и проволоки.','Постепенно наклеить тонкие слои ваты.','Сформировать мелкие детали и оставить сушиться.','Покрыть грунтом и расписать изделия.','После высыхания покрыть лаком и закрепить петли.']}
].map(t=>({...t,video:t.video||''}));

let activeFilter='Все';
let advancedFilters={levels:[],time:'all',budget:'all'};
const storedFavorites=(()=>{try{const value=JSON.parse(localStorage.getItem('istoki-favorites')||'[]');return Array.isArray(value)?value:[]}catch{return []}})();
let saved=new Set(storedFavorites.filter(id=>tutorials.some(t=>t.id===id)));
if(saved.size!==storedFavorites.length)localStorage.setItem('istoki-favorites',JSON.stringify([...saved]));
const profileDefaults={username:'anastasia_istoki',fullName:'Анастасия Орлова',socials:'',region:'Республика Чувашия',country:'Россия'};
function profileData(){try{return {...profileDefaults,...JSON.parse(localStorage.getItem('istoki-profile')||'{}')}}catch{return {...profileDefaults}}}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
const grid=document.querySelector('#tutorial-grid');
const search=document.querySelector('#tutorial-search');
const modal=document.querySelector('#filters-modal');
const advancedForm=document.querySelector('#advanced-filters-form');
const createForm=document.querySelector('#create-form');

function isMatch(t){
  const q=(search.value||'').trim().toLowerCase();
  const chipMatches=activeFilter==='Все'||(activeFilter==='До 30 минут'?t.minutes<=30:t.category===activeFilter||t.tags.includes(activeFilter));
  const levelMatches=!advancedFilters.levels.length||advancedFilters.levels.includes(t.level);
  const timeMatches=advancedFilters.time==='all'||(advancedFilters.time==='quick'&&t.minutes<=30)||(advancedFilters.time==='hour'&&t.minutes<=60);
  const budgetMatches=advancedFilters.budget==='all'||advancedFilters.budget===t.budget;
  return chipMatches&&levelMatches&&timeMatches&&budgetMatches&&(!q||[t.title,t.category,...t.tags].join(' ').toLowerCase().includes(q));
}
function optimizedImage(source){return source.replace(/_tut\.png$/,'_tut-opt.png')}
function cardMarkup(t){return `<article class="tutorial-card" data-tutorial="${t.id}" tabindex="0"><div class="tutorial-image"><img src="${optimizedImage(t.image)}" alt="${t.title}" loading="lazy" decoding="async" />${t.video?'<span class="video-badge">▶ Видео</span>':''}<button class="save-button ${saved.has(t.id)?'saved':''}" type="button" aria-label="${saved.has(t.id)?'Удалить из избранного':'Добавить в избранное'}" data-save="${t.id}">${saved.has(t.id)?'♥':'♡'}</button></div><div class="tutorial-body"><span class="tutorial-category">${t.category}</span><h3 class="tutorial-title">${t.title}</h3><div class="tutorial-meta"><span>◷ ${t.time}</span><span>◇ ${t.level.replace(' сложность','')}</span></div></div></article>`}
function renderTutorials(){const visible=tutorials.filter(isMatch);grid.innerHTML=visible.map(cardMarkup).join('');document.querySelector('#empty-state').hidden=Boolean(visible.length);updateCount();}
function updateCount(){document.querySelectorAll('.favorite-count').forEach(el=>el.textContent=saved.size?`(${saved.size})`:'' )}
function toggleSaved(id){saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('istoki-favorites',JSON.stringify([...saved]));renderTutorials();showToast(saved.has(id)?'Добавлено в избранное':'Удалено из избранного');}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(showToast.timeout);showToast.timeout=setTimeout(()=>toast.classList.remove('visible'),2400)}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.hidden=true);document.querySelector(`#${name}-view`).hidden=false;document.querySelectorAll('.site-header nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${name}`));window.scrollTo({top:0,behavior:'smooth'});}
function setTheme(theme){document.body.dataset.theme=theme;localStorage.setItem('istoki-theme',theme);const button=document.querySelector('#theme-toggle');button.querySelector('span').textContent=theme==='dark'?'☼':'◐';button.setAttribute('aria-label',theme==='dark'?'Включить светлую тему':'Включить тёмную тему');}
function syncChips(){document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c.dataset.filter===activeFilter));}
function savedImage(key){return localStorage.getItem(key)||''}
function avatarMarkup(){const avatar=savedImage('istoki-avatar');return avatar?`<img src="${avatar}" alt="Аватар пользователя" />`:'А'}
function syncHeaderAvatar(source=savedImage('istoki-avatar')){const avatar=document.querySelector('#header-avatar');if(avatar)avatar.innerHTML=source?`<img src="${source}" alt="Аватар пользователя" />`:'А'}
function showCoverPreview(source){const preview=document.querySelector('#cover-preview');if(!source)return;preview.src=source;preview.hidden=false}
function removeUpload(kind){if(kind==='cover'){localStorage.removeItem('istoki-create-cover');const input=document.querySelector('#cover-input');const preview=document.querySelector('#cover-preview');if(input)input.value='';if(preview){preview.removeAttribute('src');preview.hidden=true;}}if(kind==='avatar'){localStorage.removeItem('istoki-avatar');const input=document.querySelector('#avatar-input');const avatar=document.querySelector('.avatar-upload .profile-avatar');if(input)input.value='';if(avatar)avatar.textContent='А';syncHeaderAvatar('');}showToast('Фотография удалена')}
function saveCreateDraft(){const draft={};createForm.querySelectorAll('input:not([type="file"]), textarea, select').forEach(field=>{draft[field.name]=field.value});localStorage.setItem('istoki-tutorial-draft',JSON.stringify(draft));}
function restoreCreateDraft(){try{const draft=JSON.parse(localStorage.getItem('istoki-tutorial-draft')||'{}');Object.entries(draft).forEach(([name,value])=>{const field=createForm.querySelector(`[name="${name}"]`);if(field)field.value=value});showCoverPreview(savedImage('istoki-create-cover'));}catch{localStorage.removeItem('istoki-tutorial-draft')}}
function openFilters(){advancedForm.reset();advancedFilters.levels.forEach(level=>{const input=advancedForm.querySelector(`[name="level"][value="${level}"]`);if(input)input.checked=true});advancedForm.querySelector(`[name="time"][value="${advancedFilters.time}"]`).checked=true;advancedForm.querySelector(`[name="budget"][value="${advancedFilters.budget}"]`).checked=true;modal.hidden=false;document.body.classList.add('modal-open');}
function closeFilters(){modal.hidden=true;document.body.classList.remove('modal-open');}
function videoEmbedUrl(source){if(!source)return '';try{const url=new URL(source);const host=url.hostname.replace(/^www\./,'');if(host==='kinescope.io'||host.endsWith('.kinescope.io')){const id=url.pathname.split('/').filter(Boolean).pop();return id?`https://kinescope.io/embed/${id}`:''}if(host==='vk.com'||host.endsWith('.vk.com')||host==='vkvideo.ru'||host.endsWith('.vkvideo.ru')){if(url.pathname.includes('video_ext.php'))return url.toString();const match=url.pathname.match(/video(-?\d+)_(\d+)/);return match?`https://vk.com/video_ext.php?oid=${match[1]}&id=${match[2]}&hd=2`:url.toString()}}catch{}return ''}
function videoMarkup(t){const source=videoEmbedUrl(t.video);return source?`<section class="detail-video"><h2>Видео-туториал</h2><div class="video-embed"><iframe src="${source}" title="Видео: ${t.title}" loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div></section>`:''}
function detail(t){const history=t.history?`<div class="steps"><h2>Исторический первоисточник</h2><p>${t.history}</p></div>`:'';const steps=t.steps?.length?`<div class="steps"><h2>Пошаговая инструкция</h2><ol>${t.steps.map(step=>`<li>${step}</li>`).join('')}</ol></div>`:'';document.querySelector('#detail-view').innerHTML=`<section class="detail-page section-shell"><button class="back-link" type="button" data-route="home">← Назад к идеям</button><div class="detail-layout"><img class="detail-image" src="${optimizedImage(t.image)}" alt="${t.title}" decoding="async" /><div class="detail-info"><p class="kicker">${t.category}</p><h1>${t.title}</h1><div class="detail-tags"><span>◷ ${t.time}</span><span>◇ ${t.level}</span><span>Бюджет: ${t.budget}</span></div><p>${t.description}</p>${videoMarkup(t)}<button class="button button-wine" type="button" data-save="${t.id}">${saved.has(t.id)?'♥ В избранном':'♡ Сохранить идею'} <span>→</span></button><div class="steps"><h2>Материалы</h2><p>${t.materials}</p></div>${history}${steps}</div></div></section>`;showView('detail');}
function favorites(){const items=tutorials.filter(t=>saved.has(t.id));document.querySelector('#favorites-view').innerHTML=`<section class="favorite-page section-shell"><p class="kicker">Личный кабинет</p><h1>Избранное</h1>${items.length?`<div class="tutorial-grid">${items.map(cardMarkup).join('')}</div>`:`<p class="lead">Здесь будут ваши сохранённые идеи. Откройте каталог и нажмите сердечко на карточке.</p><button class="button button-wine" type="button" data-route="home">Перейти к идеям <span>→</span></button>`}</section>`;showView('favorites');}
function profile(){const user=profileData();document.querySelector('#profile-view').innerHTML=`<section class="profile-layout section-shell"><p class="kicker">Личный кабинет</p><h1>Моя мастерская</h1><div class="settings-grid"><section class="settings-card"><h2>Личная информация</h2><div class="avatar-upload"><div class="profile-avatar">${avatarMarkup()}</div><label>Выбрать фото<input id="avatar-input" type="file" accept="image/*" /></label><span class="upload-actions"><button class="upload-action" type="button" data-replace="avatar-input">Заменить</button><button class="upload-action remove" type="button" data-remove-upload="avatar">Удалить</button></span></div><form id="profile-form" class="profile-settings"><label>Имя пользователя<input name="username" required value="${escapeHtml(user.username)}" /></label><label>Имя и фамилия<input name="fullName" required value="${escapeHtml(user.fullName)}" /></label><label class="wide">Социальные сети<input name="socials" value="${escapeHtml(user.socials)}" placeholder="Ссылка на профиль" /></label><label>Регион<input name="region" value="${escapeHtml(user.region)}" /></label><label>Страна<input name="country" value="${escapeHtml(user.country)}" /></label><button class="button button-wine wide" type="submit">Сохранить изменения <span>→</span></button></form></section><section class="settings-card"><h2>Мои мастер-классы</h2><p>Здесь появятся ваши опубликованные видео и инструкции.</p><strong>0 опубликовано</strong><br /><button class="text-link" type="button" data-route="create">Добавить мастер-класс →</button></section><section class="settings-card"><span class="moderation-label">Скоро</span><h2>На модерации</h2><p>Добавленные пользователями видео сначала проходят проверку, чтобы материалы оставались качественными и бережными к культуре.</p><strong>Нет материалов на проверке</strong></section></div></section>`;showView('profile');}

document.addEventListener('click',e=>{
  const save=e.target.closest('[data-save]');if(save){e.stopPropagation();toggleSaved(save.dataset.save);const open=tutorials.find(t=>t.id===save.dataset.save);if(!document.querySelector('#detail-view').hidden)detail(open);return}
  const card=e.target.closest('[data-tutorial]');if(card){detail(tutorials.find(t=>t.id===card.dataset.tutorial));return}
  if(e.target.closest('#theme-toggle')){setTheme(document.body.dataset.theme==='dark'?'light':'dark');return}
  if(e.target.closest('#filters-button')){openFilters();return}
  if(e.target.closest('[data-close-filters]')){closeFilters();return}
  const replace=e.target.closest('[data-replace]');if(replace){e.preventDefault();document.querySelector(`#${replace.dataset.replace}`)?.click();return}
  const remove=e.target.closest('[data-remove-upload]');if(remove){e.preventDefault();removeUpload(remove.dataset.removeUpload);return}
  if(e.target.closest('#reset-filters')){advancedForm.reset();advancedFilters={levels:[],time:'all',budget:'all'};activeFilter='Все';search.value='';syncChips();renderTutorials();showToast('Все фильтры сброшены');return}
  const route=e.target.closest('[data-route]');if(route){const r=route.dataset.route;if(r==='favorites')favorites();else if(r==='profile')profile();else showView(r);return}
  if(e.target.closest('[data-scroll-catalog]')){showView('home');setTimeout(()=>document.querySelector('#catalog').scrollIntoView({behavior:'smooth'}),50);return}
  const category=e.target.closest('[data-category]');if(category){activeFilter=category.dataset.category==='Для дома'?'Для дома':'Все';search.value=category.dataset.category==='Вышивки'?'вышив':category.dataset.category==='Русский север'?'север':category.dataset.category==='Глиняные изделия'?'ваза':'';syncChips();renderTutorials();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});}
});
document.addEventListener('keydown',e=>{const card=e.target.closest?.('[data-tutorial]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();detail(tutorials.find(t=>t.id===card.dataset.tutorial));}if(e.key==='Escape'&&!modal.hidden)closeFilters();});
document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{activeFilter=chip.dataset.filter;syncChips();renderTutorials()}));
search.addEventListener('input',renderTutorials);
advancedForm.addEventListener('submit',e=>{e.preventDefault();advancedFilters={levels:[...advancedForm.querySelectorAll('[name="level"]:checked')].map(input=>input.value),time:advancedForm.querySelector('[name="time"]:checked').value,budget:advancedForm.querySelector('[name="budget"]:checked').value};closeFilters();renderTutorials();showToast('Фильтры применены');});
createForm.addEventListener('input',saveCreateDraft);
createForm.addEventListener('change',e=>{if(e.target.id!=='cover-input')saveCreateDraft()});
createForm.addEventListener('submit',e=>{e.preventDefault();saveCreateDraft();showToast('Черновик сохранён — спасибо за вашу идею!')});
document.addEventListener('submit',e=>{if(e.target.id==='profile-form'){e.preventDefault();localStorage.setItem('istoki-profile',JSON.stringify(Object.fromEntries(new FormData(e.target).entries())));showToast('Личная информация сохранена')}});
document.addEventListener('change',e=>{if(e.target.id==='avatar-input'&&e.target.files.length){const file=e.target.files[0];const reader=new FileReader();reader.addEventListener('load',()=>{localStorage.setItem('istoki-avatar',reader.result);const avatar=document.querySelector('.avatar-upload .profile-avatar');avatar.innerHTML=`<img src="${reader.result}" alt="Новый аватар" />`;syncHeaderAvatar(reader.result);});reader.readAsDataURL(file);showToast(`Выбран файл: ${file.name}`)}if(e.target.id==='cover-input'&&e.target.files.length){const file=e.target.files[0];const reader=new FileReader();reader.addEventListener('load',()=>{localStorage.setItem('istoki-create-cover',reader.result);showCoverPreview(reader.result);});reader.readAsDataURL(file);showToast(`Обложка добавлена: ${file.name}`)}});
window.addEventListener('hashchange',()=>{const r=location.hash.slice(1);if(r==='favorites')favorites();else if(r==='profile')profile();else if(r==='create')showView('create');else showView('home')});
setTheme(localStorage.getItem('istoki-theme')||'light');syncHeaderAvatar();restoreCreateDraft();renderTutorials();if(location.hash)window.dispatchEvent(new HashChangeEvent('hashchange'));
